# For more info on HTTP files go to https://aka.ms/vs/httpfile

POST http://localhost:5106/api/auth/login
Content-Type: application/json

{
  "email": "nasserqahtan0@gmail.com",
  "password": "nasser123"
}

###

GET http://localhost:5106/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiIiwianRpIjoiOWU4MzNlYzgtNjg4My00ZjQ0LWJlNzktZTNiZGViNDIzZmIyIiwiZXhwIjoxNzU3NDU5MzE3LCJpc3MiOiJ5b3VyLWxvY2FsLW1hdWkiLCJhdWQiOiJsb2NhbC1tYXVpLWFwcC1mb3ItdXNlcnMifQ.uBcUVkY_irLJjuxwdjNcj3bzEruZWqy5LHx55Pjs3Vw
Content-Type: application/json
###

POST http://localhost:5106/api/files/uploadfile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiIiwianRpIjoiOWU4MzNlYzgtNjg4My00ZjQ0LWJlNzktZTNiZGViNDIzZmIyIiwiZXhwIjoxNzU3NDU5MzE3LCJpc3MiOiJ5b3VyLWxvY2FsLW1hdWkiLCJhdWQiOiJsb2NhbC1tYXVpLWFwcC1mb3ItdXNlcnMifQ.uBcUVkY_irLJjuxwdjNcj3bzEruZWqy5LHx55Pjs3Vw
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary12345

------WebKitFormBoundary12345
Content-Disposition: form-data; name="file"; filename="test-audio.mp3"
Content-Type: audio/mpeg

< ./test-audio.mp3
------WebKitFormBoundary12345
Content-Disposition: form-data; name="musicMetadataDto"
Content-Type: application/json

{
    "title": "My Awesome Beat",
    "userId": -1,
    "bpm": 120,
    "genre": "Hip-Hop"
}
------WebKitFormBoundary12345--

###
GET http://localhost:5106/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2IiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiIiwianRpIjoiOWU4MzNlYzgtNjg4My00ZjQ0LWJlNzktZTNiZGViNDIzZmIyIiwiZXhwIjoxNzU3NDU5MzE3LCJpc3MiOiJ5b3VyLWxvY2FsLW1hdWkiLCJhdWQiOiJsb2NhbC1tYXVpLWFwcC1mb3ItdXNlcnMifQ.uBcUVkY_irLJjuxwdjNcj3bzEruZWqy5LHx55Pjs3Vw
Content-Type: text/html
